version: '3'

services:
  stash:
    image: stashapp/stash
    container_name: stash
    restart: unless-stopped
    network_mode: host
    environment:
      STASH_STASH: /var/lib/stash/
      STASH_CONFIG_FILE: /var/lib/stash/config.yml
      STASH_GENERATED: /var/lib/stash/generated/
      STASH_METADATA: /var/lib/stash/metadata/
      STASH_CACHE: /var/lib/stash/cache/
      STASH_PORT: 9999
    labels:
      traefik.enable: true
      traefik.http.services.stash.loadbalancer.server.port: 9999
      traefik.http.routers.stash.rule: Host(`stash`)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /containers/stash:/var/lib/stash
      - /tank/media/xxx/photos:/tank/media/xxx/photos
      - /tank/media/xxx/videos:/tank/media/xxx/videos
